# Generated by Django 6.1 on 2026-08-13 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("adults", models.PositiveIntegerField(default=1)),
                ("children", models.PositiveIntegerField(default=0)),
                ("pets", models.PositiveIntegerField(default=0)),
                ("remote_work", models.BooleanField(default=False)),
                ("hobby", models.BooleanField(default=False)),
                ("bikes", models.PositiveIntegerField(default=0)),
                (
                    "storage_level",
                    models.CharField(
                        choices=[
                            ("small", "Mało"),
                            ("medium", "Średnio"),
                            ("large", "Dużo"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_area",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calculations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
