# Generated by Django 6.1 on 2026-08-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="name",
            field=models.CharField(default="Moje obliczenie", max_length=120),
        ),
    ]
