# Generated by Django 6.1 on 2026-08-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0002_calculation_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="minimum_area",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="calculation",
            name="recommended_rooms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
