# Generated by Django 6.1 on 2026-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calculator", "0003_calculation_minimum_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="area_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="calculation",
            name="extra_room_recommendation",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
